title: ALEDO Docs
description: Documentación operativa y técnica interna

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# opcional
color_scheme: light
search_enabled: true
